[workspace]

[package]
name = "realm"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "*"

vulkano = "0.26.0"
vulkano-shaders = "0.26.0"
vulkano-win = "0.26.0"
winit = "0.25"

slotmap = "1.0"
cgmath = "0.18"
ndshape = "0.1"
height-mesh = "0.1"

combine = "4.6.2"
